- name: Remove Packer artifact
  community.proxmox.proxmox_kvm:
    api_host: "#{PROXMOX_NODE}#"
    api_user: "#{PROXMOX_USERNAME}#"
    api_password: "#{PROXMOX_TOKEN}#"
    name: "{{ VM_NAME }}"
    node: "#{PROXMOX_NODE}#"
    state: absent
  delegate_to: localhost