name: Host 02 Build

on:
  workflow_dispatch:
    inputs:
      os_type:
        type: choice
        description: Choose OS type for Packer build
        options:
          - linux
          - windows 

env:
  LINUX_VM_NAME: pkr-ubuntu-2404
  WINDOWS_VM_NAME: pkr-win2025-dc          
          
jobs:
  init_and_build:
    name: Packer Build Job 🏗️
    runs-on: Self-Hosted
    environment: "Host 02"

    steps:

      - name: Checkout 🔔
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Ansible 🖥️
        run: |
          sudo apt update && sudo apt install ansible -y

      - name: Install Packer 🖥️
        run: |
          ansible-playbook packer_install.yml
        working-directory: ./ansible

      - name: Map Secrets to Environment Variables 🗺️ 
        uses: oNaiPs/secrets-to-env-action@be0f849b5f57bce2c73624f006578c3b16e98e0c # v1.7
        with:
            secrets: ${{ toJSON(secrets) }}        

      - name: Replace Tokens 🪙
        uses: qetza/replacetokens-action@e693b63d0fac410b1ae61d82cbc540c12f205556 # v1.2.1
        with:
          sources: '**/*.*'
          variables: '[${{ toJSON(secrets) }}]'

      - name: Remove existing Packer artifacts 📦
        run: | 
          if [[ ${{ github.event.inputs.os_type }} == "linux" ]]; then
            PACKER_VM_NAME="${{ env.LINUX_VM_NAME }}"
          else  
            PACKER_VM_NAME="${{ env.WINDOWS_VM_NAME }}"

          ansible-playbook packer_artifact_removal.yml --extra-vars "VM_NAME=$PACKER_VM_NAME"
        working-directory: ./ansible

      - name: Run Packer Init and Build 🚀
        id: terraformPlan
        run: |
          echo "Running Packer build for OS Type: ${{ github.event.inputs.os_type }}"
          packer init .
          packer build --force .
        working-directory: ./build/${{ github.event.inputs.os_type }}

